### PR TITLE
feat(CommandHandler): add blockDM options to block dm message

### PR DESCRIPTION
**Pull request by Waxaranai**
I don't know if this good enough to be merged, but i hope so

### CODE REVIEW

**Comment by Papaia** [comment]
This should be made to fire `CommandHandler#commandBlocked` similarly to how `Command#channel` does it, which is a better approach in my opinion.
That way you can have it block DMs by default but allow some commands through DMs, then same for guilds.

**Comment by Waxaranai** [comment]
> 
> 
> This should be made to fire `CommandHandler#commandBlocked` similarly to how `Command#channel` does it, which is a better approach in my opinion.
> That way you can have it block DMs by default but allow some commands through DMs, then same for guilds.

Yeah, but i don't wanna assign a channel option everytime i create a `Command`

**Comment by Waxaranai** [comment]
or maybe add a `defaultChannelType` to the `CommandHandlerOptions` so we don't need to a assign a `channel` options, we only need it when it for `DM` or something else.

**Comment by Papaia** [comment]
What I mean is a `channel` option for the command handler that could be overridden by the command specific one.
Also, you currently don't fire `commandBlocked`.

**Comment by Waxaranai** [comment]
Yeah, i just realize that. so instead of blocking the DM message, i should just create a options in the `CommandHandler` for override the `channel` options in `Command` if the options not set by the dev?

**Comment by Papaia** [comment]
More like have a command handler option which can be overridden by the commands.
But then you'd have to add another option for `channel` which allows both, as to not completely limit to ONLY DMs or ONLY guilds

**Comment by Waxaranai** [comment]
Alright, im gonna close this pull.

**Pull request closed without merging**
