### PR TITLE
MongooseProvider

### PR DESCRIPTION
**Pull request by Zerefdev**
If you consider adding a Mongoose provider, send me a "request changes" so I can add changes I made [here](https://github.com/Zerefdev/akairo-mongoose)

### CODE REVIEW

**Comment by MelvinIdema** [comment]
Almost perfect for my use-case! Thank you. We should definitely add this to Akairo. But there's one big problem though. In your example you have set "id" to required. This means that everytime we set a value we get an error that id is required. Or at least, that's what I'm getting. The set function should set a whole document.

**Comment by Zerefdev** [comment]
Hello,
> This means that everytime we set a value we get an error that id is required. 

No. The "id" field is there to check if a guild has already a document in the database or not. You don't touch it at all when you use the set or get functions.

> The set function should set a whole document.

the set function modifies the "settings" field in the database which is an object by default (specified in the schema). the reason for that is the possibility to add more information about the guild if needed, e.g.: join date, ownerId..etc

image

>It seems like it cannot create a document if it does not exist

the `getDocument` function creates a document automatically if it does not exist

see: https://github.com/Zerefdev/akairo-mongoose/blob/3151f61e0a323494a7776de4303c2f62f3a9c731/index.js#L54
and
https://github.com/Zerefdev/akairo-mongoose/blob/3151f61e0a323494a7776de4303c2f62f3a9c731/index.js#L97

I will soon add the ability to set some kind of configuration to the schema and settings.

There is also an example here:
https://github.com/Zerefdev/akairo-mongoose/tree/master/example

**Comment by Suyashtnt** [comment]
I've tried this and I can't wait for it to get merged!

**Comment by Zerefdev** [comment]
@Suyashtnt use this https://github.com/Zerefdev/akairo-mongoose

**Comment by Suyashtnt** [comment]
> @Suyashtnt use this [Zerefdev/akairo-mongoose](https://github.com/Zerefdev/akairo-mongoose)

I am currently :)

**Comment by Suyashtnt** [comment]
Ok I now have an error when i try to use your prefix example,
`(node:79400) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'prefix' of undefined
    at MongooseProvider.get (C:\Users\Home\Documents\EmojiBoi\node_modules\akairo-mongoose\index.js:56:45)
    at CommandHandler.prefix (C:\Users\Home\Documents\EmojiBoi\index.ts:21:42)
    at CommandHandler.parseCommand (C:\Users\Home\Documents\EmojiBoi\node_modules\discord-akairo\src\struct\commands\CommandHandler.js:770:65)
    at CommandHandler.handle (C:\Users\Home\Documents\EmojiBoi\node_modules\discord-akairo\src\struct\commands\CommandHandler.js:361:37)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(node:79400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a 
catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79400) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
worked yesterday but since I updated my dependencies it stopped.
Package.json + index.ts
[files.zip](https://github.com/discord-akairo/discord-akairo/files/4756787/files.zip)

**Comment by Zerefdev** [comment]
@Suyashtnt please post here https://github.com/Zerefdev/akairo-mongoose/issues
and update your mongoose model to https://github.com/Zerefdev/akairo-mongoose#model-example

**Comment by Suyashtnt** [comment]
It worked

**Comment by IlyasDiker** [comment]
Thank you, that helped me alot!

**Comment by Shqrp** [comment]
Sorry that I'm commenting on an old PR, but this seems the perfect place to ask. Is it possible to use multiple models with the provider? Because I want to have a model for the Guild, and then a model for a "Case" (basically a moderation event, that gets added on every warn, mute, ban, etc.) that would be inside the Guild.

**Pull request merged**
