### PR TITLE
chore(deps): remove peer-deps as per npm@7

### PR DESCRIPTION
**Pull request by Papaia**
npm@7 would install peer deps automatically ([source](https://github.com/npm/rfcs/blob/latest/accepted/0025-install-peer-deps.md)), causing `sqlite` and `sequelize` to be installed with every akairo install, along with a version of discord.js that is not the latest, so this PR removes them.

They are still mentioned in the README, which should be more than enough.

### CODE REVIEW

**Comment by pizzafox** [comment]
Does setting them as optional dependencies fix this? Removing Discord.js from the peer deps seems like a bad idea.

**Comment by Papaia** [comment]
Making them optional is like keeping them peer after npm@7 is released.

And for discord.js, it would install akairo, your discord.js version, **and** the peer discord.js, which would mean one of two:
 - You'd have to update the akairo peer each time discord.js is updated
 - You'd have two different versions of discord.js as deps on the same project, which is just a waste of space.

**Comment by 1Computer1** [comment]
It seems there are no solutions to truly optional dependencies yet, and I don't want to break anyone's build steps so this will stay for now.

**Comment by Papaia** [comment]
Okay sure, but please be ready because as soon as npm 7 goes up this would be a problem.

**Pull request merged**
