### PR TITLE
Updated docs(TypeCasters) to master version

### PR DESCRIPTION
**Pull request by GamesProSeif**
### Why to merge
TypeCasters docs were outdated, and were only applied to the stable version of TypeCasters.
- Updated docs for `docs/arguments/custom.md`
- Updated docs for `docs/arguments/functions.md`

While there might be other outdated documentation, I wanted to fix this first cause it confused a lot of people who install master for the first time (and only read the guide and not the actual reference).

### Issue
One more thing, I was going to make an issue about this, but it really doesn't belong to this repo.

The links that are used to link between pages, for example `docs/arguments/functions.md#119`, they do work on GitHub, but they don't work on the GitHub pages website. So... you might do something in discord.js's Vue app since it's a virtual DOM/single- page app (don't know what to call it) and it considers `./` as the index page, and not the page you're on.  
Meaning, doing `./compose.md` from `functions.md` will only forward to  
https://discord-akairo.github.io/compose.md (which does not exist)
but not https://discord-akairo.github.io/#/docs/main/master/arguments/compose.  
So yeah you might want to do something about that. 👀

Love your work <3 and good luck with your projects :)

### CODE REVIEW

**Comment by NightYoshi370** [comment]
> ### With Message
Let's say we want to add a type that would get a role based on the input.  
This means we need access to the guild through the message.  
Good thing the second parameter is the message!  

Obviously this isn't the case anymore is it

**Comment by GamesProSeif** [comment]
Good catch, @NightYoshi370! Going to commit the change.

**Comment by NightYoshi370** [comment]
By the way, I was wondering why we switched the parameter order in the first place. Is there any benefit to have message come before the actual argument itself?

**Comment by GamesProSeif** [comment]
I have no idea, even in the updating page:

> Type functions previously would be passed `(phrase, message, args)`.  
They now pass `(message, phrase)`.  
The previous arguments can be accessed by using a generator for arguments.

It doesn't say the reason.
From my personal view, it's better, cause it attracts people to the idea that the parameter `message` exists in the function haha. They previously would just do `type: (phrase) => {...}`, but now they all know it. But on the other hand, you don't use `message` that much, so you always have to add it without using it :/ I usually do `(_, phrase)` and ignore it completely.

**Comment by gazmull** [comment]
As far as I know the reason is because it's for consistency where most methods implement message as the first parameter, and thus probably creating confusion to some people.

**Pull request merged**
