### PR TITLE
fix: client#setInterval is no longer exist

### PR DESCRIPTION
**Pull request by KagChi**
[ref](https://github.com/discordjs/discord.js/pull/6113)

### CODE REVIEW

**Comment by SkyBlockDev** [comment]
You forgot line 725 in the command handler

**Comment by KagChi** [comment]
> You forgot line 725 in the command handler

thank you for reminding me

**Comment by SkyBlockDev** [comment]
also 727 lol

**Comment by SerenModz21** [comment]
u should make sure of the `unref` method like djs has done with their built-in timers

**Comment by KagChi** [comment]
sorry for the bad contribution, it's better for someone else to make pr

**Pull request closed without merging**
